export const countries_en = [
  { name: 'Afghanistan', countryCode: 'AF' },
  { name: 'Albania', countryCode: 'AL' },
  { name: 'Algeria', countryCode: 'DZ' },
  { name: 'Andorra', countryCode: 'AD' },
  { name: 'Angola', countryCode: 'AO' },
  { name: 'Antigua and Barbuda', countryCode: 'AG' },
  { name: 'Argentina', countryCode: 'AR' },
  { name: 'Armenia', countryCode: 'AM' },
  { name: 'Australia', countryCode: 'AU' },
  { name: 'Austria', countryCode: 'AT' },
  { name: 'Azerbaijan', countryCode: 'AZ' },
  { name: 'Bahamas', countryCode: 'BS' },
  { name: 'Bahrain', countryCode: 'BH' },
  { name: 'Bangladesh', countryCode: 'BD' },
  { name: 'Barbados', countryCode: 'BB' },
  { name: 'Belarus', countryCode: 'BY' },
  { name: 'Belgium', countryCode: 'BE' },
  { name: 'Belize', countryCode: 'BZ' },
  { name: 'Benin', countryCode: 'BJ' },
  { name: 'Bhutan', countryCode: 'BT' },
  { name: 'Bolivia', countryCode: 'BO' },
  { name: 'Bosnia and Herzegovina', countryCode: 'BA' },
  { name: 'Botswana', countryCode: 'BW' },
  { name: 'Brazil', countryCode: 'BR' },
  { name: 'Brunei', countryCode: 'BN' },
  { name: 'Bulgaria', countryCode: 'BG' },
  { name: 'Burkina Faso', countryCode: 'BF' },
  { name: 'Burundi', countryCode: 'BI' },
  { name: 'Cabo Verde', countryCode: 'CV' },
  { name: 'Cambodia', countryCode: 'KH' },
  { name: 'Cameroon', countryCode: 'CM' },
  { name: 'Canada', countryCode: 'CA' },
  { name: 'Central African Republic', countryCode: 'CF' },
  { name: 'Chad', countryCode: 'TD' },
  { name: 'Chile', countryCode: 'CL' },
  { name: 'China', countryCode: 'CN' },
  { name: 'Colombia', countryCode: 'CO' },
  { name: 'Comoros', countryCode: 'KM' },
  { name: 'Congo', countryCode: 'CG' },
  { name: 'Costa Rica', countryCode: 'CR' },
  { name: 'Croatia', countryCode: 'HR' },
  { name: 'Cuba', countryCode: 'CU' },
  { name: 'Cyprus', countryCode: 'CY' },
  { name: 'Czech Republic', countryCode: 'CZ' },
  { name: 'Denmark', countryCode: 'DK' },
  { name: 'Djibouti', countryCode: 'DJ' },
  { name: 'Dominica', countryCode: 'DM' },
  { name: 'Dominican Republic', countryCode: 'DO' },
  { name: 'Ecuador', countryCode: 'EC' },
  { name: 'Egypt', countryCode: 'EG' },
  { name: 'El Salvador', countryCode: 'SV' },
  { name: 'Equatorial Guinea', countryCode: 'GQ' },
  { name: 'Eritrea', countryCode: 'ER' },
  { name: 'Estonia', countryCode: 'EE' },
  { name: 'Eswatini', countryCode: 'SZ' },
  { name: 'Ethiopia', countryCode: 'ET' },
  { name: 'Fiji', countryCode: 'FJ' },
  { name: 'Finland', countryCode: 'FI' },
  { name: 'France', countryCode: 'FR' },
  { name: 'Gabon', countryCode: 'GA' },
  { name: 'Gambia', countryCode: 'GM' },
  { name: 'Georgia', countryCode: 'GE' },
  { name: 'Germany', countryCode: 'DE' },
  { name: 'Ghana', countryCode: 'GH' },
  { name: 'Greece', countryCode: 'GR' },
  { name: 'Grenada', countryCode: 'GD' },
  { name: 'Guatemala', countryCode: 'GT' },
  { name: 'Guinea', countryCode: 'GN' },
  { name: 'Guinea-Bissau', countryCode: 'GW' },
  { name: 'Guyana', countryCode: 'GY' },
  { name: 'Haiti', countryCode: 'HT' },
  { name: 'Honduras', countryCode: 'HN' },
  { name: 'Hungary', countryCode: 'HU' },
  { name: 'Iceland', countryCode: 'IS' },
  { name: 'India', countryCode: 'IN' },
  { name: 'Indonesia', countryCode: 'ID' },
  { name: 'Iran', countryCode: 'IR' },
  { name: 'Iraq', countryCode: 'IQ' },
  { name: 'Ireland', countryCode: 'IE' },
  { name: 'Israel', countryCode: 'IL' },
  { name: 'Italy', countryCode: 'IT' },
  { name: 'Jamaica', countryCode: 'JM' },
  { name: 'Japan', countryCode: 'JP' },
  { name: 'Jordan', countryCode: 'JO' },
  { name: 'Kazakhstan', countryCode: 'KZ' },
  { name: 'Kenya', countryCode: 'KE' },
  { name: 'Kiribati', countryCode: 'KI' },
  { name: 'Kuwait', countryCode: 'KW' },
  { name: 'Kyrgyzstan', countryCode: 'KG' },
  { name: 'Laos', countryCode: 'LA' },
  { name: 'Latvia', countryCode: 'LV' },
  { name: 'Lebanon', countryCode: 'LB' },
  { name: 'Lesotho', countryCode: 'LS' },
  { name: 'Liberia', countryCode: 'LR' },
  { name: 'Libya', countryCode: 'LY' },
  { name: 'Liechtenstein', countryCode: 'LI' },
  { name: 'Lithuania', countryCode: 'LT' },
  { name: 'Luxembourg', countryCode: 'LU' },
  { name: 'Madagascar', countryCode: 'MG' },
  { name: 'Malawi', countryCode: 'MW' },
  { name: 'Malaysia', countryCode: 'MY' },
  { name: 'Maldives', countryCode: 'MV' },
  { name: 'Mali', countryCode: 'ML' },
  { name: 'Malta', countryCode: 'MT' },
  { name: 'Marshall Islands', countryCode: 'MH' },
  { name: 'Mauritania', countryCode: 'MR' },
  { name: 'Mauritius', countryCode: 'MU' },
  { name: 'Mexico', countryCode: 'MX' },
  { name: 'Micronesia', countryCode: 'FM' },
  { name: 'Moldova', countryCode: 'MD' },
  { name: 'Monaco', countryCode: 'MC' },
  { name: 'Mongolia', countryCode: 'MN' },
  { name: 'Montenegro', countryCode: 'ME' },
  { name: 'Morocco', countryCode: 'MA' },
  { name: 'Mozambique', countryCode: 'MZ' },
  { name: 'Myanmar', countryCode: 'MM' },
  { name: 'Namibia', countryCode: 'NA' },
  { name: 'Nauru', countryCode: 'NR' },
  { name: 'Nepal', countryCode: 'NP' },
  { name: 'Netherlands', countryCode: 'NL' },
  { name: 'New Zealand', countryCode: 'NZ' },
  { name: 'Nicaragua', countryCode: 'NI' },
  { name: 'Niger', countryCode: 'NE' },
  { name: 'Nigeria', countryCode: 'NG' },
  { name: 'North Korea', countryCode: 'KP' },
  { name: 'North Macedonia', countryCode: 'MK' },
  { name: 'Norway', countryCode: 'NO' },
  { name: 'Oman', countryCode: 'OM' },
  { name: 'Pakistan', countryCode: 'PK' },
  { name: 'Palau', countryCode: 'PW' },
  { name: 'Palestine', countryCode: 'PS' },
  { name: 'Panama', countryCode: 'PA' },
  { name: 'Papua New Guinea', countryCode: 'PG' },
  { name: 'Paraguay', countryCode: 'PY' },
  { name: 'Peru', countryCode: 'PE' },
  { name: 'Philippines', countryCode: 'PH' },
  { name: 'Poland', countryCode: 'PL' },
  { name: 'Portugal', countryCode: 'PT' },
  { name: 'Qatar', countryCode: 'QA' },
  { name: 'Romania', countryCode: 'RO' },
  { name: 'Russia', countryCode: 'RU' },
  { name: 'Rwanda', countryCode: 'RW' },
  { name: 'Saint Kitts and Nevis', countryCode: 'KN' },
  { name: 'Saint Lucia', countryCode: 'LC' },
  { name: 'Saint Vincent and the Grenadines', countryCode: 'VC' },
  { name: 'Samoa', countryCode: 'WS' },
  { name: 'San Marino', countryCode: 'SM' },
  { name: 'Sao Tome and Principe', countryCode: 'ST' },
  { name: 'Saudi Arabia', countryCode: 'SA' },
  { name: 'Senegal', countryCode: 'SN' },
  { name: 'Serbia', countryCode: 'RS' },
  { name: 'Seychelles', countryCode: 'SC' },
  { name: 'Sierra Leone', countryCode: 'SL' },
  { name: 'Singapore', countryCode: 'SG' },
  { name: 'Slovakia', countryCode: 'SK' },
  { name: 'Slovenia', countryCode: 'SI' },
  { name: 'Solomon Islands', countryCode: 'SB' },
  { name: 'Somalia', countryCode: 'SO' },
  { name: 'South Africa', countryCode: 'ZA' },
  { name: 'South Korea', countryCode: 'KR' },
  { name: 'South Sudan', countryCode: 'SS' },
  { name: 'Spain', countryCode: 'ES' },
  { name: 'Sri Lanka', countryCode: 'LK' },
  { name: 'Sudan', countryCode: 'SD' },
  { name: 'Suriname', countryCode: 'SR' },
  { name: 'Sweden', countryCode: 'SE' },
  { name: 'Switzerland', countryCode: 'CH' },
  { name: 'Syria', countryCode: 'SY' },
  { name: 'Taiwan', countryCode: 'TW' },
  { name: 'Tajikistan', countryCode: 'TJ' },
  { name: 'Tanzania', countryCode: 'TZ' },
  { name: 'Thailand', countryCode: 'TH' },
  { name: 'Timor-Leste', countryCode: 'TL' },
  { name: 'Togo', countryCode: 'TG' },
  { name: 'Tonga', countryCode: 'TO' },
  { name: 'Trinidad and Tobago', countryCode: 'TT' },
  { name: 'Tunisia', countryCode: 'TN' },
  { name: 'Turkey', countryCode: 'TR' },
  { name: 'Turkmenistan', countryCode: 'TM' },
  { name: 'Tuvalu', countryCode: 'TV' },
  { name: 'Uganda', countryCode: 'UG' },
  { name: 'Ukraine', countryCode: 'UA' },
  { name: 'United Arab Emirates', countryCode: 'AE' },
  { name: 'United Kingdom', countryCode: 'GB' },
  { name: 'United States of America', countryCode: 'US' },
  { name: 'Uruguay', countryCode: 'UY' },
  { name: 'Uzbekistan', countryCode: 'UZ' },
  { name: 'Vanuatu', countryCode: 'VU' },
  { name: 'Vatican City', countryCode: 'VA' },
  { name: 'Venezuela', countryCode: 'VE' },
  { name: 'Vietnam', countryCode: 'VN' },
  { name: 'Yemen', countryCode: 'YE' },
  { name: 'Zambia', countryCode: 'ZM' },
  { name: 'Zimbabwe', countryCode: 'ZW' },
];

export const countries_es = [

  { name: 'Afganistán', countryCode: 'AF' },
  { name: 'Albania', countryCode: 'AL' },
  { name: 'Alemania', countryCode: 'DE' },
  { name: 'Andorra', countryCode: 'AD' },
  { name: 'Angola', countryCode: 'AO' },
  { name: 'Anguila', countryCode: 'AI' },
  { name: 'Antigua y Barbuda', countryCode: 'AG' },
  { name: 'Antártida', countryCode: 'AQ' },
  { name: 'Arabia Saudita', countryCode: 'SA' },
  { name: 'Arabia Saudita', countryCode: 'SA' },
  { name: 'Argelia', countryCode: 'DZ' },
  { name: 'Argentina', countryCode: 'AR' },
  { name: 'Armenia', countryCode: 'AM' },
  { name: 'Aruba', countryCode: 'AW' },
  { name: 'Australia', countryCode: 'AU' },
  { name: 'Austria', countryCode: 'AT' },
  { name: 'Azerbaiyán', countryCode: 'AZ' },
  { name: 'Bahamas', countryCode: 'BS' },
  { name: 'Bahréin', countryCode: 'BH' },
  { name: 'Bangladés', countryCode: 'BD' },
  { name: 'Barbados', countryCode: 'BB' },
  { name: 'Belice', countryCode: 'BZ' },
  { name: 'Benín', countryCode: 'BJ' },
  { name: 'Bermudas', countryCode: 'BM' },
  { name: 'Bielorrusia', countryCode: 'BY' },
  { name: 'Bolivia', countryCode: 'BO' },
  { name: 'Bonaire', countryCode: 'BQ' },
  { name: 'Bosnia y Herzegovina', countryCode: 'BA' },
  { name: 'Botsuana', countryCode: 'BW' },
  { name: 'Brasil', countryCode: 'BR' },
  { name: 'Brunéi', countryCode: 'BN' },
  { name: 'Bulgaria', countryCode: 'BG' },
  { name: 'Burkina Faso', countryCode: 'BF' },
  { name: 'Burundi', countryCode: 'BI' },
  { name: 'Bután', countryCode: 'BT' },
  { name: 'Bélgica', countryCode: 'BE' },
  { name: 'Cabo Verde', countryCode: 'CV' },
  { name: 'Camboya', countryCode: 'KH' },
  { name: 'Camerún', countryCode: 'CM' },
  { name: 'Canadá', countryCode: 'CA' },
  { name: 'Chad', countryCode: 'TD' },
  { name: 'Chequia', countryCode: 'CZ' },
  { name: 'Chile', countryCode: 'CL' },
  { name: 'China', countryCode: 'CN' },
  { name: 'Chipre', countryCode: 'CY' },
  { name: 'Colombia', countryCode: 'CO' },
  { name: 'Comoras', countryCode: 'KM' },
  { name: 'Costa Rica', countryCode: 'CR' },
  { name: 'Costa de Marfil', countryCode: 'CI' },
  { name: 'Croacia', countryCode: 'HR' },
  { name: 'Cuba', countryCode: 'CU' },
  { name: 'Curazao', countryCode: 'CW' },
  { name: 'Dinamarca', countryCode: 'DK' },
  { name: 'Dominica', countryCode: 'DM' },
  { name: 'Ecuador', countryCode: 'EC' },
  { name: 'Egipto', countryCode: 'EG' },
  { name: 'El Salvador', countryCode: 'SV' },
  { name: 'Emiratos Árabes Unidos', countryCode: 'AE' },
  { name: 'Eritrea', countryCode: 'ER' },
  { name: 'Eslovaquia', countryCode: 'SK' },
  { name: 'Eslovenia', countryCode: 'SI' },
  { name: 'España', countryCode: 'ES' },
  { name: 'Estados Unidos de América', countryCode: 'US' },
  { name: 'Estonia', countryCode: 'EE' },
  { name: 'Etiopía', countryCode: 'ET' },
  { name: 'Filipinas', countryCode: 'PH' },
  { name: 'Finlandia', countryCode: 'FI' },
  { name: 'Fiyi', countryCode: 'FJ' },
  { name: 'Francia', countryCode: 'FR' },
  { name: 'Gabón', countryCode: 'GA' },
  { name: 'Gambia', countryCode: 'GM' },
  { name: 'Georgia', countryCode: 'GE' },
  { name: 'Georgia del Sur e Islas Sandwich del Sur', countryCode: 'GS' },
  { name: 'Ghana', countryCode: 'GH' },
  { name: 'Gibraltar', countryCode: 'GI' },
  { name: 'Granada', countryCode: 'GD' },
  { name: 'Grecia', countryCode: 'GR' },
  { name: 'Groenlandia', countryCode: 'GL' },
  { name: 'Guadalupe', countryCode: 'GP' },
  { name: 'Guam', countryCode: 'GU' },
  { name: 'Guatemala', countryCode: 'GT' },
  { name: 'Guayana Francesa', countryCode: 'GF' },
  { name: 'Guernsey', countryCode: 'GG' },
  { name: 'Guinea', countryCode: 'GN' },
  { name: 'Guinea Ecuatorial', countryCode: 'GQ' },
  { name: 'Guinea-Bissau', countryCode: 'GW' },
  { name: 'Guyana', countryCode: 'GY' },
  { name: 'Haití', countryCode: 'HT' },
  { name: 'Honduras', countryCode: 'HN' },
  { name: 'Hong Kong', countryCode: 'HK' },
  { name: 'Hungría', countryCode: 'HU' },
  { name: 'India', countryCode: 'IN' },
  { name: 'Indonesia', countryCode: 'ID' },
  { name: 'Iraq', countryCode: 'IQ' },
  { name: 'Irlanda', countryCode: 'IE' },
  { name: 'Irán', countryCode: 'IR' },
  { name: 'Isla Bouvet', countryCode: 'BV' },
  { name: 'Isla Norfolk', countryCode: 'NF' },
  { name: 'Isla de Man', countryCode: 'IM' },
  { name: 'Isla de Navidad', countryCode: 'CX' },
  { name: 'Islandia', countryCode: 'IS' },
  { name: 'Islas Caimán', countryCode: 'KY' },
  { name: 'Islas Cocos', countryCode: 'CC' },
  { name: 'Islas Cook', countryCode: 'CK' },
  { name: 'Islas Feroe', countryCode: 'FO' },
  { name: 'Islas Heard y McDonald', countryCode: 'HM' },
  { name: 'Islas Malvinas', countryCode: 'FK' },
  { name: 'Islas Malvinas', countryCode: 'FK' },
  { name: 'Islas Marianas del Norte', countryCode: 'MP' },
  { name: 'Islas Marshall', countryCode: 'MH' },
  { name: 'Islas Salomón', countryCode: 'SB' },
  { name: 'Islas Turcas y Caicos', countryCode: 'TC' },
  { name: 'Islas Vírgenes Británicas', countryCode: 'VG' },
  { name: 'Islas Vírgenes de los Estados Unidos', countryCode: 'VI' },
  { name: 'Israel', countryCode: 'IL' },
  { name: 'Italia', countryCode: 'IT' },
  { name: 'Jamaica', countryCode: 'JM' },
  { name: 'Japón', countryCode: 'JP' },
  { name: 'Jersey', countryCode: 'JE' },
  { name: 'Jordania', countryCode: 'JO' },
  { name: 'Kazajistán', countryCode: 'KZ' },
  { name: 'Kenia', countryCode: 'KE' },
  { name: 'Kirguistán', countryCode: 'KG' },
  { name: 'Kiribati', countryCode: 'KI' },
  { name: 'Kuwait', countryCode: 'KW' },
  { name: 'Laos', countryCode: 'LA' },
  { name: 'Lesoto', countryCode: 'LS' },
  { name: 'Letonia', countryCode: 'LV' },
  { name: 'Liberia', countryCode: 'LR' },
  { name: 'Libia', countryCode: 'LY' },
  { name: 'Liechtenstein', countryCode: 'LI' },
  { name: 'Lituania', countryCode: 'LT' },
  { name: 'Luxemburgo', countryCode: 'LU' },
  { name: 'Líbano', countryCode: 'LB' },
  { name: 'Macao', countryCode: 'MO' },
  { name: 'Macedonia del Norte', countryCode: 'MK' },
  { name: 'Madagascar', countryCode: 'MG' },
  { name: 'Malasia', countryCode: 'MY' },
  { name: 'Malaui', countryCode: 'MW' },
  { name: 'Maldivas', countryCode: 'MV' },
  { name: 'Malta', countryCode: 'MT' },
  { name: 'Malí', countryCode: 'ML' },
  { name: 'Marruecos', countryCode: 'MA' },
  { name: 'Marruecos', countryCode: 'MA' },
  { name: 'Martinica', countryCode: 'MQ' },
  { name: 'Mauricio', countryCode: 'MU' },
  { name: 'Mauritania', countryCode: 'MR' },
  { name: 'Mayotte', countryCode: 'YT' },
  { name: 'Micronesia', countryCode: 'FM' },
  { name: 'Moldavia', countryCode: 'MD' },
  { name: 'Mongolia', countryCode: 'MN' },
  { name: 'Montenegro', countryCode: 'ME' },
  { name: 'Montserrat', countryCode: 'MS' },
  { name: 'Mozambique', countryCode: 'MZ' },
  { name: 'Myanmar', countryCode: 'MM' },
  { name: 'México', countryCode: 'MX' },
  { name: 'Mónaco', countryCode: 'MC' },
  { name: 'Namibia', countryCode: 'NA' },
  { name: 'Nauru', countryCode: 'NR' },
  { name: 'Nepal', countryCode: 'NP' },
  { name: 'Nicaragua', countryCode: 'NI' },
  { name: 'Nigeria', countryCode: 'NG' },
  { name: 'Niue', countryCode: 'NU' },
  { name: 'Noruega', countryCode: 'NO' },
  { name: 'Nueva Caledonia', countryCode: 'NC' },
  { name: 'Nueva Zelanda', countryCode: 'NZ' },
  { name: 'Níger', countryCode: 'NE' },
  { name: 'Omán', countryCode: 'OM' },
  { name: 'Pakistán', countryCode: 'PK' },
  { name: 'Palaos', countryCode: 'PW' },
  { name: 'Panamá', countryCode: 'PA' },
  { name: 'Papúa Nueva Guinea', countryCode: 'PG' },
  { name: 'Paraguay', countryCode: 'PY' },
  { name: 'Países Bajos', countryCode: 'NL' },
  { name: 'Perú', countryCode: 'PE' },
  { name: 'Pitcairn', countryCode: 'PN' },
  { name: 'Polinesia Francesa', countryCode: 'PF' },
  { name: 'Polonia', countryCode: 'PL' },
  { name: 'Portugal', countryCode: 'PT' },
  { name: 'Puerto Rico', countryCode: 'PR' },
  { name: 'Qatar', countryCode: 'QA' },
  { name: 'Reino Unido', countryCode: 'GB' },
  { name: 'República Centroafricana', countryCode: 'CF' },
  { name: 'República Democrática del Congo', countryCode: 'CD' },
  { name: 'República Dominicana', countryCode: 'DO' },
  { name: 'República del Congo', countryCode: 'CG' },
  { name: 'Reunión', countryCode: 'RE' },
  { name: 'Ruanda', countryCode: 'RW' },
  { name: 'Rumania', countryCode: 'RO' },
  { name: 'Rusia', countryCode: 'RU' },
  { name: 'Sahara Occidental', countryCode: 'EH' },
  { name: 'Samoa', countryCode: 'WS' },
  { name: 'San Bartolomé', countryCode: 'BL' },
  { name: 'San Cristóbal y Nieves', countryCode: 'KN' },
  { name: 'San Marino', countryCode: 'SM' },
  { name: 'San Martín (parte francesa)', countryCode: 'MF' },
  { name: 'San Pedro y Miquelón', countryCode: 'PM' },
  { name: 'San Vicente y las Granadinas', countryCode: 'VC' },
  { name: 'Santa Elena, Ascensión y Tristán de Acuña', countryCode: 'SH' },
  { name: 'Santa Lucía', countryCode: 'LC' },
  { name: 'Santo Tomé y Príncipe', countryCode: 'ST' },
  { name: 'Senegal', countryCode: 'SN' },
  { name: 'Serbia', countryCode: 'RS' },
  { name: 'Seychelles', countryCode: 'SC' },
  { name: 'Sierra Leona', countryCode: 'SL' },
  { name: 'Singapur', countryCode: 'SG' },
  { name: 'Sint Maarten (parte holandesa)', countryCode: 'SX' },
  { name: 'Siria', countryCode: 'SY' },
  { name: 'Somalia', countryCode: 'SO' },
  { name: 'Sri Lanka', countryCode: 'LK' },
  { name: 'Suazilandia', countryCode: 'SZ' },
  { name: 'Sudáfrica', countryCode: 'ZA' },
  { name: 'Sudán', countryCode: 'SD' },
  { name: 'Sudán del Sur', countryCode: 'SS' },
  { name: 'Suecia', countryCode: 'SE' },
  { name: 'Suiza', countryCode: 'CH' },
  { name: 'Surinam', countryCode: 'SR' },
  { name: 'Svalbard y Jan Mayen', countryCode: 'SJ' },
  { name: 'Tailandia', countryCode: 'TH' },
  { name: 'Taiwán', countryCode: 'TW' },
  { name: 'Tanzania', countryCode: 'TZ' },
  { name: 'Tayikistán', countryCode: 'TJ' },
  { name: 'Territorios Australes Franceses', countryCode: 'TF' },
  { name: 'Timor Oriental', countryCode: 'TL' },
  { name: 'Togo', countryCode: 'TG' },
  { name: 'Tokelau', countryCode: 'TK' },
  { name: 'Tonga', countryCode: 'TO' },
  { name: 'Trinidad y Tobago', countryCode: 'TT' },
  { name: 'Turkmenistán', countryCode: 'TM' },
  { name: 'Turquía', countryCode: 'TR' },
  { name: 'Tuvalu', countryCode: 'TV' },
  { name: 'Túnez', countryCode: 'TN' },
  { name: 'Ucrania', countryCode: 'UA' },
  { name: 'Uganda', countryCode: 'UG' },
  { name: 'Uruguay', countryCode: 'UY' },
  { name: 'Uzbekistán', countryCode: 'UZ' },
  { name: 'Vanuatu', countryCode: 'VU' },
  { name: 'Venezuela', countryCode: 'VE' },
  { name: 'Vietnam', countryCode: 'VN' },
  { name: 'Wallis y Futuna', countryCode: 'WF' },
  { name: 'Yemen', countryCode: 'YE' },
  { name: 'Yibuti', countryCode: 'DJ' },
  { name: 'Zambia', countryCode: 'ZM' },
  { name: 'Zimbabue', countryCode: 'ZW' },

];
